### ISSUE TITLE
definition of the pitch-yaw angles

### ISSUE THREAD

**Issue by wjtan99** [laodar/cnn_head_pose_estimator#3]
Hi, can you explain a little bit the exact definition of the two numbers in the pitch-yaw angles? 
Thanks a lot.

**Comment by laodar** [comment]
http://www-prima.inrialpes.fr/perso/Gourier/Faces/HPDatabase.html
so sorry for that my model don't works well in real scene, it seems to be sensitive to the background and lights because of the oversimplified public dataset,maybe we can synthesis more data with better background based on HPDatabase.
